routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/welcome', function () {
    return view('welcome');
});


// public route
Route::get('/', 'Pub\AccueilController@index')->name('P_accueil');
Route::resource('/P_article' , 'Pub\ArticleController')->only('index','show');
Route::resource('/P_media' , 'Pub\MediaArticleController')->only('show');
Route::resource('/P_menu' , 'Pub\MenuController')->only('show');


// admin route
    // auth
    //      ...->middleware('auth');

Route::resource('/A_menu' , 'Admin\AdminMenuController')->only('index','show');
Route::resource('/A_article' , 'Admin\ArticleController')->middleware('auth');
Route::get('/A_articleDeleted' , 'Admin\ArticleController@deletedArticle')->name('A_articlesDeleted');
Route::get('/A_articleDeleted/{id}' , 'Admin\ArticleController@showDeleted')->name('showDeleted');
Route::resource('/A_accueil' , 'Admin\Accueil\AccueilController')->only('index');
Route::resource('/A_carousel' , 'Admin\Accueil\CarouselController')->only('index','edit' , 'store' ,'newSlide');
Route::get('/A_carousel_newSlide' , 'Admin\Accueil\CarouselController@newSlide')->name('newSlide');
Route::resource('/A_media' , 'Admin\Accueil\MediaController')->only('index','show' , 'create', 'store' );
Route::post('/A_media_delete', 'Admin\Accueil\MediaController@delete')->name('A_media_delete');


// Route::get('/addArticle', function ($menus) {
//     return view('admin.article.addArticle' , [ 'menus' => $menus]);
// })->name('addArticle');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
    use SoftDeletes;

    protected $table = 'articles';

    public function carousel()
    {
        return $this->belongsTo('App/Carousel');
    }
    
    public function articleMedia()
    {
        return $this->hasOne('App\MediaArticle');
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Article;
use App\Carousel;
use App\Http\Requests\StoreArticle;
use App\Menu;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpKernel\HttpCache\Store;
use Illuminate\Support\Str;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.article.articles', [
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
             'articles' => Article::get()
        ] );
    }

    public function deletedArticle(){
        $deleted_articles = Article::onlyTrashed()
                            ->get();
        return view('admin.article.deletedArticles', [
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
            'articles' => $deleted_articles
        ] );
    }

    public function showDeleted($id)
    {
        $article = Article::onlyTrashed()
                    ->where('id', $id)
                    ->first();
        return view('admin.article.article', [
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
            'article' => $article
        ] );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.article.addArticle', [
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get()
        ] );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreArticle $request)
    {
        $request->validate([
            'media' => 'required'
        ]);

        $article = new Article();
        $article->title = $request->input('title');
        $article->content = $request->input('content');
        $article->created_by = 'user aute';
        if ($request->hasFile('media')) {
            $article->media = $request->file('media')->store('article' , 'public');
            $media_type = Str::lower($request->file('media')->extension());
            // dd($media_type);
            if ($media_type == 'svg' || $media_type == 'png' || $media_type == 'jpeg' || 
                $media_type == 'gif' || $media_type == 'jpg' || $media_type == 'psd' || 
                $media_type == 'pdf' || $media_type == 'ia' ) {
                    $article->media_type = 'img';
            }elseif($media_type == 'mp4' ){
                $article->media_type = 'video';
            }
        }
        $article->save();

        $request->session()->flash('status' , "article créé");

        return redirect()->route('A_article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.article.article', [
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
            'article' => Article::findOrFail($id)
        ] );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.article.edit' ,[
                'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
                'article' => Article::findOrFail($id)
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreArticle $request, $id)
    {
        // dd($request);
        $article = Article::findOrFail($id);

        $article->title = $request->title;
        $article->content = $request->content;
        if ($request->hasFile('media')) {
            if (Storage::delete($article->media)) {
                $article->media = $request->file('media')->store('article' , 'public');
            }
        }
        $article->save();

        $request->session()->flash('status' , "Article ($id) modifiée");

        return redirect()->route('A_article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    { 
        // dd($id);
        if (DB::table('articles')
                                ->join('carousels', 'carousels.article_id', '=', 'articles.id')
                                ->where('carousels.article_id', $id)
                                ->where('carousels.selected', 1)
                                ->select('carousels.*')
                                ->get()->count() > 0) {
            return 'article is selected can not be deleted';
        }
        else{
            Article::destroy($id);

            Session::flash('status' , "Article ($id) supprimer");
            
            return redirect()->route('A_article.index');
        }
    }
}

app/Http/Controllers/Pub/ArticleController.php
<?php

namespace App\Http\Controllers\Pub;

use App\Article;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('public.article', [
            'article' => Article::findOrFail($id)
        ] );
    }
}

resources/views/admin/article/addArticle.blade.php
@extends('admin.A_master')

@section('admin_content')
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-12 pl-2">
          <h1 class="m-0 text-dark">ajouter un article</h1>
        </div><!-- /.col -->
      
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

    <form method="POST" action="{{ route('A_article.store') }}" enctype="multipart/form-data">
      @csrf
        
      @include('admin.article.forme')
      <button type="submit" class="btn btn-primary">ajouter</button>
      <a href="{{url()->previous()}}" class="btn btn-danger">annuler</a>
    </form>

@endsection

resources/views/admin/article/article.blade.php
@extends('admin.A_master')

@section('admin_content')
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6 pl-2">
          <h1 class="m-0 text-dark">Détail de l'article</h1>
        </div><!-- /.col -->
        <div class="col-sm-6 pr-2">
          <a href="{{ url()->previous() }}" class="btn btn-danger header-btn">retoure</a>
          @if ($article->deleted_at==NULL)
            <a href="{{ route('A_article.edit', [ $article->id ]) }}" class="btn btn-primary header-btn">modifier</a>
            <a href="{{ route('A_article.create') }}" class="btn btn-success header-btn">nouvel article</a>
            <a href="{{ route('A_article.index') }}" class="btn btn-secondary header-btn">liste article</a>
          @endif
          
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  {{-- content --}}
  <div class="content">
    <h3 class="article-title">{{$article->title}}</h3>
    <div class="body-content">
      <p class="text-content mb-5">
        {!!$article->Content!!}
      </p>
      <img src="{{asset('/storage//'. $article->media )}}" class="media" alt="">
    </div>
    
  </div>
  {{-- /.content --}}
@endsection

resources/views/admin/article/articles.blade.php
@extends('admin.A_master')

@section('admin_content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6 pl-2">
        <h1 class="m-0 text-dark">liste des articles</h1>
      </div><!-- /.col -->
      <div class="col-sm-6 pr-2">
        <a href="{{ route('A_article.create') }}" class="btn btn-success header-btn">ajouter un article</a>
        <a href="{{ route('A_articlesDeleted') }}" class="btn btn-secondary header-btn">articles supprimés</a>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

@if (session()->has('status'))
  <h3 class="flash-msg">
    {{ session()->get('status') }}
  </h3>
@endif

<table class="table table-striped col-auto">
    <thead>
      <tr class="row">
        <th scope="col">#</th>
        <th scope="col" class="col-5">titre</th>
        <th scope="col" class="col">Créé à</th>
        <th scope="col" class="col-4">action</th>
      </tr>
    </thead>
    <tbody>
    @foreach ($articles as $article)
        <tr class="row">
            <th scope="row">{{$article->id}}</th>
            <td class="col-5">{{$article->title}}</td>
            <td class="col">{{$article->created_at}}</td>
            <td class="content-fluid col-4">
                <a href="{{ route('A_article.show', [ $article->id ]) }}" class="btn btn-success" >consulté</a>
                <a href="{{ route('A_article.edit', [ $article->id ]) }}" class="btn btn-primary" >modifier</a>
                
                <form method="POST" action="{{ route('A_article.destroy', [ $article->id ]) }}" id="delete-{{$article->id}}"
                    style="display: inline;">
                  @csrf
                  @method('delete')
                  <button type="button" class="btn btn-danger delete-article" id="{{$article->id}}" 
                          data-toggle="modal" data-target="#modal-danger">
                    supprimer
                  </button>
                </form>
            </td>
        </tr>
    @endforeach
    </tbody>
  </table>


  <div class="modal fade" id="modal-danger">
    <div class="modal-dialog">
      <div class="modal-content bg-danger">
        <div class="modal-header">
          <h4 class="modal-title">confirmez votre choix</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>voulez-vous vraiment supprimer l'article&hellip;<span class="art_id"></span></p>
        </div>
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-outline-light" data-dismiss="modal">annuler</button>
          <button type="button" class="btn btn-outline-light" id="modal-validation">supprimer</button>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
  <!-- /.modal -->


@endsection

resources/views/admin/article/deletedArticles.blade.php
@extends('admin.A_master')

@section('admin_content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6 pl-2">
        <h1 class="m-0 text-dark">articles supprimés</h1>
      </div><!-- /.col -->
      <div class="col-sm-6 pr-2">
        <a href="{{ url()->previous() }}" class="btn btn-danger header-btn">retoure</a>
        <a href="{{ route('A_article.index') }}" class="btn btn-secondary header-btn">liste article</a>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<table class="table table-striped col-auto">
    <thead>
      <tr class="row">
        <th scope="col">#</th>
        <th scope="col" class="col-5">titre</th>
        <th scope="col" class="col">supprimé à</th>
        <th scope="col" class="col">action</th>
      </tr>
    </thead>
    <tbody>
    @foreach ($articles as $article)
        <tr class="row">
            <th scope="row">{{$article->id}}</th>
            <td class="col-5">{{$article->title}}</td>
            <td class="col">{{$article->deleted_at}}</td>
            <td class="content-fluid col">
                <a href="{{ route('showDeleted', [ $article->id ]) }}" class="btn btn-success" >consulté</a>
            </td>
        </tr>
    @endforeach
    </tbody>
  </table>

@endsection

resources/views/admin/article/edit.blade.php
@extends('admin.A_master')

@section('admin_content')

  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6 pl-2">
          <h1 class="m-0 text-dark">Modifier l'article</h1>
        </div><!-- /.col -->
        <div class="col-sm-6 pr-2">
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

    <form method="POST" action="{{ route('A_article.update', [ $article->id ]) }}"  enctype="multipart/form-data">
        @csrf
        @method('PUT')        
        
        @include('admin.article.forme')
        <input type="submit" class="btn btn-primary" value="Modifier">
        <a href="{{url()->previous()}}" class="btn btn-danger">annuler</a>

    </form>

@endsection

resources/views/admin/article/forme.blade.php
<div class="form-group">
    <label for="title">Titre</label>
    <input name="title" type="text" class="form-control" id="title" placeholder="Titre de l'article" value="{{ old('title' , $article->title ?? NULL ) }}">
    @if ($errors->first('title'))
        <span class="error-name">* {{ $errors->first('title') }}</span>
    @endif
  </div>
  <div class="form-group">
    <label for="content">Text</label>
    <section class="">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-outline card-info">
            <div class="card-header">
              <h3 class="card-title">
                Styler votre text
                <small>Simple and fast</small>
              </h3>
              <!-- tools box -->
              <div class="card-tools">
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
              <!-- /. tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body pad">
              <div class="mb-3">
                <textarea class="textarea content-fluid" name="content" placeholder="Place some text here"
                          style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" >{{ old('content' , $article->Content ?? NULL ) }}</textarea>
              </div>
            </div>
          </div>
        </div>
        <!-- /.col-->
        <div class="error col-md-12 ">
          @if ($errors->first('content'))
            <span class="error-name">* {{ $errors->first('content') }}</span>
          @endif  
        </div>
      </div>
      <!-- ./row -->
    </section>
  </div>
  <div class="form-group">
      <label for="media">media :</label>
      <input name="media" type="file" class="form-control-file" value="{{ old('content' , $article->media ?? NULL ) }}">
    </div>