routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/welcome', function () {
    return view('welcome');
});


// public route
Route::get('/', 'Pub\AccueilController@index')->name('P_accueil');
Route::resource('/P_article' , 'Pub\ArticleController')->only('index','show');
Route::resource('/P_media' , 'Pub\MediaArticleController')->only('show');
Route::resource('/P_menu' , 'Pub\MenuController')->only('show');


// admin route
    // auth
    //      ...->middleware('auth');

Route::resource('/A_menu' , 'Admin\AdminMenuController')->only('index','show');
Route::resource('/A_article' , 'Admin\ArticleController')->middleware('auth');
Route::get('/A_articleDeleted' , 'Admin\ArticleController@deletedArticle')->name('A_articlesDeleted');
Route::get('/A_articleDeleted/{id}' , 'Admin\ArticleController@showDeleted')->name('showDeleted');
Route::resource('/A_accueil' , 'Admin\Accueil\AccueilController')->only('index');
Route::resource('/A_carousel' , 'Admin\Accueil\CarouselController')->only('index','edit' , 'store' ,'newSlide');
Route::get('/A_carousel_newSlide' , 'Admin\Accueil\CarouselController@newSlide')->name('newSlide');
Route::resource('/A_media' , 'Admin\Accueil\MediaController')->only('index','show' , 'create', 'store' );
Route::post('/A_media_delete', 'Admin\Accueil\MediaController@delete')->name('A_media_delete');


// Route::get('/addArticle', function ($menus) {
//     return view('admin.article.addArticle' , [ 'menus' => $menus]);
// })->name('addArticle');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Carousel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Carousel extends Model
{
    public function articles()
    {
        return $this->hasMany('App/Article');
    }
}

app/Http/Controllers/Admin/Accueil/AccueilController.php
<?php

namespace App\Http\Controllers\Admin\Accueil;

use App\Content;
use App\Http\Controllers\Controller;
use App\Menu;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AccueilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // dd( Menu::where( 'title' , 'accueil' )->with('contents')->get());

        return view('admin.Accueil.accueil', [
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
            'categories' => DB::table('menus')
                                    ->join('contents', 'contents.menu_id', '=', 'menus.id')
                                    ->where('menus.title', 'accueil')
                                    ->select('menus.title As M_title' , 'contents.*' )
                                    ->get()
        ] );
    }
}

app/Http/Controllers/Admin/Accueil/CarouselController.php
<?php

namespace App\Http\Controllers\Admin\Accueil;

use App\Article;
use App\Carousel;
use App\Http\Controllers\Controller;
use App\Menu;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Str;
use phpDocumentor\Reflection\Types\Null_;

class CarouselController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.Accueil.carousel.silds', [
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
            'slids' =>  DB::table('articles')
                                    ->join('carousels', 'carousels.article_id', '=', 'articles.id')
                                    ->where('carousels.selected', 1)
                                    ->select('articles.*', 'carousels.id as carousel_id' ,
                                            'carousels.updated_at as carousel_update')
                                    ->get()
        ] );
    }


    public function store(Request $request)
    {
    // if modification du slide
        if ($request->old_id) {
            $old = Carousel::findOrFail($request->old_id);
            $old->selected = 0 ;
            $old->save();

            $request->session()->flash('status' , "Diapositive modifiée");    
        }
    // nouveau slide ou modification
        $carousel = new Carousel();
        if($request->id_choisie == null ){
            return Redirect::back();
        }
        $carousel->article_id = $request->id_choisie;
        $carousel->selected = 1;
        $media_type = null;
        if ($request->hasFile('back_img')) {
            $media_type = $request->file('back_img')->extension();
        }
            if ($media_type == 'svg' || $media_type == 'png' || $media_type == 'jpeg' || 
                $media_type == 'gif' || $media_type == 'jpg' ) {

                    $carousel->back_img = $request->file('back_img')->store('carousel' , 'public');
            }elseif( $media_type == null ){
                $carousel->back_img = "carousel/default.jpeg";
            }else{
                return 'file selected is not image';
            }
        $carousel->save();

        if (!$request->old_id) {
            $request->session()->flash('status' , "Nouvelle diapositive crée");    
        }
        return redirect()->route('A_carousel.index');
    }

    public function edit($id)
    {
        return view('admin.accueil.carousel.edit' ,[
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
            'articles' =>  Article::whereNotIn('articles.id', 
                                                Carousel::where('selected', 1)
                                                ->select('article_id')
                                                ->get())
                                    ->select('*')
                                    ->get(),    
            'carousel_id' => $id
        ]);
    }

    public function newSlide()
    {
        return view('admin.accueil.carousel.newSlide' ,[
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
            'articles' =>  Article::whereNotIn('articles.id', 
                                                Carousel::where('selected', 1)
                                                ->select('article_id')
                                                ->get())
                                    ->select('*')
                                    ->get()
        ]);
    }
}

app/Http/Controllers/Admin/Accueil/MediaController.php
<?php

namespace App\Http\Controllers\Admin\Accueil;

use App\Article;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreMedia;
use App\Media;
use App\MediaArticle;
use App\Menu;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class MediaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.Accueil.media.media_categorie', [
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
            'media_categories' => Media::all() 
            ]);
    }

    public function create()
    {
        // DB::connection()->enableQueryLog();
        $media_articles = MediaArticle::select('article_id')->get();
        $articles = Article::whereNotIn('id' , $media_articles)
                            ->get() ;
        return view('admin.accueil.media.media_add_article' , [
            'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
            'media_categories' => Media::all() ,
            'articles' => $articles
        ]);
    }

    public function store(StoreMedia $request)
    {
        $media_art = MediaArticle::all();
        // dd($media_art);
        foreach ($media_art as $key ) {
            if ($key != null ) {
                // dd($key);
                if ($key->media_id == $request->media_id && $key->article_id == $request->article_selected) {
                    return back()->with('status' , 'Déjà existe');
                }
            }
        }
        foreach ( $request->article_selected as $article ) {
            $media_article = new MediaArticle();
            $media_article->token =  $request->_token ;
            $media_article->media_id =  $request->media_id ;
            $media_article->article_id =  $article ;
            $media_article->save();
        }

        $request->session()->flash('status' , "Articles ajouter");

        return redirect()->route('A_media.index');
    }

    public function show($id)
    {
        $articles = DB::table('articles')
                        ->join('media_articles', 'media_articles.article_id', '=', 'articles.id')
                        ->join('media', 'media.id', '=', 'media_articles.media_id')
                        ->where([
                            ['media_articles.media_id' , $id],
                             ['media_articles.deleted_at' , NULL]
                        ])
                        ->select('articles.*' , 'media_articles.*' ,'media.title as media_title' )
                        ->get();

        return view('admin.Accueil.media.media_articles', [
                'menus' => Menu::where('parent_id' , NULL)->with('sousMenu')->get(),
                'articles' =>$articles  
        ]);
    }

    public function delete(Request $request)
    {
        MediaArticle::where([
            ['article_id', $request->article_id],
            ['media_id', $request->media_id]
        ])->delete();

        $request->session()->flash('status' , "Article supprimer");

        return redirect()->route('A_media.show', [ $request->media_id])->with('msg', 'Deleted ');
    }
}

app/Http/Controllers/Pub/AccueilController.php
<?php

namespace App\Http\Controllers\Pub;

use App\Article;
use App\Http\Controllers\Controller;
use App\Media;
use App\MediaArticle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AccueilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('public.accueil' , [
            'carousel' =>  DB::table('articles')
                                ->join('carousels', 'carousels.article_id', '=', 'articles.id')
                                ->where('carousels.selected', 1)
                                ->select('articles.*', 'carousels.id as carousel_id' , 'carousels.back_img')
                                ->get(),
            'media' => Media::all(),
            'accueil' =>  DB::table('media_articles')
                                ->join('articles', 'media_articles.article_id', '=', 'articles.id')
                                ->where('media_articles.media_id', 1)
                                ->limit(10)
                                ->select('articles.*')
                                ->get(),
            'press' =>  DB::table('media_articles')
                                ->join('articles', 'media_articles.article_id', '=', 'articles.id')
                                ->where('media_articles.media_id', 2)
                                ->limit(10)
                                ->select('articles.*')
                                ->get(),
            'conseil' =>  DB::table('media_articles')
                                ->join('articles', 'media_articles.article_id', '=', 'articles.id')
                                ->where('media_articles.media_id', 3)
                                ->limit(10)
                                ->select('articles.*')
                                ->get(),

        ]);
    }
}

resources/views/admin/accueil/carousel/edit.blade.php
@extends('admin.A_master')

@section('admin_content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6 pl-2">
        <h1 class="m-0 text-dark">liste des articles</h1>
      </div><!-- /.col -->
      <div class="col-sm-6 pr-2">
        <a href="{{ route('A_article.create') }}" class="btn btn-success header-btn">ajouter un article</a>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<form action="{{route('A_carousel.store')}}" method="POST" class="send-forme" enctype="multipart/form-data">
  @csrf
    
  <input type="hidden" name="old_id" value="{{ $carousel_id }}">
  <input type="hidden" class="id_choisie mx-2 px-1" name="id_choisie" id="id_choisie" value="">
  <div class="my-3">
    <label class="mx-2 px-1">article choisi</label>
  <input type="number" class=" id_choisie mx-2 px-1" disabled="disabled">
  <input type="text" class="article_name mx-2 px-1" disabled="disabled">
  </div>
  
  <div class="my-3">
  <label class="mx-2 px-1" for="">Back groud image</label>
  <input type="file" name="back_img" >
  </div>
  
  <input type="submit" class="btn btn-primary mx-2 px-1 align-content-center" value="Modifier">
  <a href="{{url()->previous()}}" class="btn btn-danger">annuler</a>
</form>

<table class="table table-striped col-auto">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">titre</th>
        <th scope="col">action</th>
        <th scope="col">selectionne</th>
      </tr>
    </thead>
    <tbody>
    @foreach ($articles as $article)
        <tr>
            <th scope="row">{{$article->id}}</th>
            <td>{{$article->title}}</td>
            <td class="content-fluid">
                <a href="{{ route('A_article.show', [ $article->id ]) }}" class="btn btn-success" >consulté</a>
            </td>
            <td>
                  <input type="radio" name="new-slid" class="slid-select" id="{{$article->title}}" value="{{$article->id}}">
            </td>
        </tr>
    @endforeach
    </tbody>
  </table>


@endsection

resources/views/admin/accueil/carousel/newSlide.blade.php
@extends('admin.A_master')

@section('admin_content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6 pl-2">
        <h1 class="m-0 text-dark">liste des articles</h1>
      </div><!-- /.col -->
      <div class="col-sm-6 pr-2">
        <a href="{{ route('A_article.create') }}" class="btn btn-success header-btn">ajouter un article</a>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<form action="{{route('A_carousel.store')}}" method="POST" class=" send-forme" enctype="multipart/form-data">
  @csrf
    
  <input type="hidden" name="old_id" value="{{ null }}">
  <input type="hidden" class="id_choisie mx-2 px-1" name="id_choisie" id="id_choisie" value="">
  <div class="my-3">
    <label class="mx-2 px-1">Article choisi</label>
  <input type="number" class=" id_choisie mx-2 px-1" disabled="disabled">
  <input type="text" class="article_name mx-2 px-1" disabled="disabled">
  </div>
  
  <div class="my-3">
  <label class="mx-2 px-1" for="">Back groud image</label>
  <input type="file" name="back_img" >
  </div>
  
  <input type="submit" class="btn btn-primary mx-2 px-1 align-content-center" value="ajouter">
  <a href="{{url()->previous()}}" class="btn btn-danger">annuler</a>
</form>

<table class="table table-striped col-auto">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">titre</th>
        <th scope="col">action</th>
        <th scope="col">selectionne</th>
      </tr>
    </thead>
    <tbody>
    @foreach ($articles as $article)
        <tr>
            <th scope="row">{{$article->id}}</th>
            <td>{{$article->title}}</td>
            <td class="content-fluid">
                <a href="{{ route('A_article.show', [ $article->id ]) }}" class="btn btn-success" >consulté</a>
            </td>
            <td>
                  <input type="radio" name="new-slid" class="slid-select" id="{{$article->title}}" value="{{$article->id}}">
            </td>
        </tr>
    @endforeach
    </tbody>
  </table>


@endsection

resources/views/admin/accueil/carousel/silds.blade.php
@extends('admin.A_master')

@section('admin_content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 pl-2">
                    <h1 class="m-0 text-dark">Carousel slides</h1>
                </div><!-- /.col -->
                <div class="col-sm-6 pr-2">
                    <a href="{{ route('A_article.create') }}" class="btn btn-success header-btn">nouvel article</a>
                    @if ( $slids->count()  < 3 )
                        <a href="{{ route('newSlide') }}" class="btn btn-primary header-btn">nouveau slide</a>
                    @endif
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    {{-- flash message --}}
    @if (session()->has('status'))
        <h3 class="flash-msg">
            {{ session()->get('status') }}
        </h3>
    @endif
    {{-- end flash message --}}

    <table class="table table-striped col-auto">
        <thead>
          <tr class="row">
            <th scope="col" >#</th>
            <th scope="col" class="col-6">article titre</th>
            <th scope="col" class="col">date Sellection</th>
            <th scope="col" class="col">action</th>
          </tr>
        </thead>
        <tbody>
        @foreach ($slids as $slid)
            <tr class="row">
                <th scope="row">{{$slid->id}}</th>
                <td class="col-6">{{$slid->title}}</td>
                <td class="col">{{$slid->carousel_update}}</td>
                <td class="content-fluid col">
                    <a href="{{ route('A_article.show', [ $slid->id ]) }}" class="btn btn-success" >consulté</a>
                    <a href="{{ route('A_carousel.edit', [ $slid->carousel_id ]) }}" class="btn btn-primary" >modifier</a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    
    
@endsection