routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/welcome', function () {
    return view('welcome');
});


// public route
Route::get('/', 'Pub\AccueilController@index')->name('P_accueil');
Route::resource('/P_article' , 'Pub\ArticleController')->only('index','show');
Route::resource('/P_media' , 'Pub\MediaArticleController')->only('show');
Route::resource('/P_menu' , 'Pub\MenuController')->only('show');


// admin route
    // auth
    //      ...->middleware('auth');

Route::resource('/A_menu' , 'Admin\AdminMenuController')->only('index','show');
Route::resource('/A_article' , 'Admin\ArticleController')->middleware('auth');
Route::get('/A_articleDeleted' , 'Admin\ArticleController@deletedArticle')->name('A_articlesDeleted');
Route::get('/A_articleDeleted/{id}' , 'Admin\ArticleController@showDeleted')->name('showDeleted');
Route::resource('/A_accueil' , 'Admin\Accueil\AccueilController')->only('index');
Route::resource('/A_carousel' , 'Admin\Accueil\CarouselController')->only('index','edit' , 'store' ,'newSlide');
Route::get('/A_carousel_newSlide' , 'Admin\Accueil\CarouselController@newSlide')->name('newSlide');
Route::resource('/A_media' , 'Admin\Accueil\MediaController')->only('index','show' , 'create', 'store' );
Route::post('/A_media_delete', 'Admin\Accueil\MediaController@delete')->name('A_media_delete');


// Route::get('/addArticle', function ($menus) {
//     return view('admin.article.addArticle' , [ 'menus' => $menus]);
// })->name('addArticle');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/A_master.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/../plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="/../plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- JQVMap -->
  <link rel="stylesheet" href="/../plugins/jqvmap/jqvmap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/../dist/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="/../plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="/../plugins/daterangepicker/daterangepicker.css">
  <!-- summernote -->
  <link rel="stylesheet" href="/../plugins/summernote/summernote-bs4.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  {{-- Mes styles --}}
    <link rel="stylesheet" href="{{ mix('css/admin/A_style.css')}}"> 
  
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
    @include('admin.sideBar')


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    
    @yield('admin_content')

  </div>




  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="/../plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/../plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="/../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="/../plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="/../plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="/../plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="/../plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="/../plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/../plugins/moment/moment.min.js"></script>
<script src="/../plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/../plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="/../plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="/../plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/../dist/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/../dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/../dist/js/demo.js"></script>
{{-- my scripts --}}
<script src="{{ mix('js/A_script.js')}}"></script>
</body>
</html>

resources/views/admin/sideBar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/../dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info user-name">
          
          <li class="dropdown">
            <a id="navbarDropdown" class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }} <span class="caret"></span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
          </li>

        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            @foreach ($menus as $menu)
              @php($sousM = 0)
              @foreach ($menu->sousMenu as $sousmenu)
                @if ( $sousmenu->id )
                    @php($sousM = 1)
                    @break
                @endif
              @endforeach
              @if ($sousM == 1)
                <li class="nav-item has-treeview">
                  <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-plus-square"></i>
                    <p>
                      {{ $menu->title }}
                      <i class="right fas fa-angle-left"></i>
                    </p>
                  </a>
                  <ul class="nav nav-treeview pl-4">
                    @foreach ($menu->sousMenu as $sousmenu)
                      <li class="nav-item">
                        <a href="{{ route('A_menu.show' , [$sousmenu->id]) }}" class="nav-link">
                          <i class="far fa-circle nav-icon"></i>
                          <p>{{ $sousmenu->title }}</p>
                        </a>
                      </li>
                    @endforeach
                    </ul>
                </li>
              @endif
              @if ($sousM == 0)
                <li class="nav-item">
                  <a href="{{ route('A_menu.show' , [$menu->id]) }}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>{{ $menu->title }}</p>
                  </a>
                </li>
              @endif
            @endforeach
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>